export default {
    points: [
        {
            id: 0,
            type: 0,
            create_date: '2023-11-11',
            reference: 'TK0012',
            name: 'Điểm A',
            address: 'AAAA',
            city: 'Hà Nội',
            zipcode: '84',
            phone: '0123123123',
            manager_reference: '',
            manager_id: null,
            link_point_id: null,
            link_point_reference: '',
        },
        {
            id: 1,
            type: 1,
            create_date: '2023-11-11',
            reference: 'GD0013',
            name: 'Điểm B',
            address: 'BBBB',
            city: 'Hà Nội',
            zipcode: '84',
            phone: '0123123123',
            manager_reference: '',
            manager_id: null,
            link_point_id: 0,
            link_point_reference: 'TK0012',
        },
    ],
    managerAccounts: [
        {
            id: 0,
            reference: 'ABC',
            type: 0,
            create_date: "2023-12-08",
            last_seen: "2023-12-08",
            name: 'Hùng',
            sex: "male",
            email: 'hung@gmail.com',
            birthday: '1993-11-03',
            phone: '09123123123',
            point_reference: '',
            point_id: null,
            username: 'hung',
            password: 'test',
        },
    ],
    exchangingDelivery: [
        {
            id: 0,
            delivery_id: "DH1235",
            package_id: "VN1236HN",
            create_date: "2023-12-01",
            send_date: "2023-12-08",
            expected_date: "2023-12-08",
            arrived_date: "",
            current_from: "gathering",
            from_point_id: "TK0012",
            current_dest: "exchanging",
            dest_point_id: "GD0015",
            status: "not-resolved",
            is_delivered: 0,
            receive_address: "",
            receive_name: "",
            receive_phone: "",
            note: "aaa ",
        }
    ],
    exchangingPackage: [
        {
            id: 0,
            package_id: "VN1235HN",
            send_name: "Dũng",
            send_date: "2023-12-08",
            send_phone: "0912345677",
            send_address: "Tầng 1, Tòa nhà Báo Lao Động, 06 P. Phạm Văn Bạch, Yên Hoà, Cầu Giấy, Hà Nội",
            send_point_id: "0120036",
            receive_name: "Hoàng",
            receive_phone: "09987654321",
            receive_address: "73-75 Thủ Khoa Huân, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh 70000, Việt Nam",
            receive_point_id: "0120040",
            current_from: "gathering",
            from_point_id: "TK0012",
            current_dest: "exchanging",
            dest_point_id: "GD0015",
            status: "received",
            main_cost: 60000,
            other_cost: 10000,
            gtgt_cost: 0,
            other_service_cost: 0,
            total_cost: 77000,
            vat: 10,
            package_type: 1,
            instruction_type: 0,
            weight: 10,
            special_service: '',
            note: 'Hàng dễ vỡ',
            cod: 0,
            receive_other_cost: 0,
            items: [
                {
                    item_name: "Đồng hồ",
                    quantity: 1,
                    value: 100000,
                },
                {
                    item_name: "Điện thoại",
                    quantity: 1,
                    value: 10000000,
                },
            ]
        },
        {
            id: 1,
            package_id: "VN1236HN",
            send_name: "Dũng",
            send_date: "2023-12-07",
            send_phone: "0912345677",
            send_address: "Tầng 1, Tòa nhà Báo Lao Động, 06 P. Phạm Văn Bạch, Yên Hoà, Cầu Giấy, Hà Nội",
            send_point_id: "0120036",
            receive_name: "Hoàng",
            receive_phone: "09987654321",
            receive_address: "73-75 Thủ Khoa Huân, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh 70000, Việt Nam",
            receive_point_id: "0120040",
            current_from: "gathering",
            from_point_id: "TK0012",
            current_dest: "exchanging",
            dest_point_id: "GD0015",
            status: "in-transit",
            main_cost: 80000,
            other_cost: 10000,
            gtgt_cost: 0,
            other_service_cost: 0,
            total_cost: 99000,
            vat: 10,
            package_type: 1,
            instruction_type: null,
            weight: 10,
            special_service: '',
            note: '',
            cod: 0,
            receive_other_cost: 0,
            items: [
            ]
        },
        {
            id: 2,
            package_id: "VN1237HN",
            send_name: "Dũng",
            send_date: "2023-12-10",
            send_phone: "0912345677",
            send_address: "Tầng 1, Tòa nhà Báo Lao Động, 06 P. Phạm Văn Bạch, Yên Hoà, Cầu Giấy, Hà Nội",
            send_point_id: "0120036",
            receive_name: "Hoàng",
            receive_phone: "09987654321",
            receive_address: "73-75 Thủ Khoa Huân, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh 70000, Việt Nam",
            receive_point_id: "0120040",
            current_from: "gathering",
            from_point_id: "TK0012",
            current_dest: "exchanging",
            dest_point_id: "GD0015",
            status: "not-received",
            main_cost: 30000,
            other_cost: 10000,
            gtgt_cost: 0,
            other_service_cost: 0,
            total_cost: 44000,
            vat: 10,
            package_type: 0,
            instruction_type: null,
            weight: 10,
            special_service: '',
            note: '',
            cod: 0,
            receive_other_cost: 0,
            items: [
                {
                    item_name: "Tài liệu",
                    quantity: null,
                    value: 100000,
                },
            ]
        },

    ],
    gatheringDelivery: [
        {
            id: 0,
            delivery_id: "DH1235",
            package_id: "VN1236HN",
            create_date: "2023-12-01",
            send_date: "2023-12-08",
            expected_date: "2023-12-08",
            arrived_date: "",
            current_from: "gathering",
            from_point_id: "TK0012",
            current_dest: "exchanging",
            dest_point_id: "GD0015",
            status: "not-resolved",
            is_delivered: 0,
            receive_address: "",
            receive_name: "",
            receive_phone: "",
            note: "aaa ",
        },
        {
            id: 1,
            delivery_id: "DH1236",
            package_id: "VN1237HN",
            create_date: "2023-12-08",
            send_date: "2023-12-08",
            expected_date: "2023-12-08",
            arrived_date: "",
            current_from: "exchanging",
            from_point_id: "GD0013",
            current_dest: "receiver",
            dest_point_id: "",
            status: "not-resolved",
            is_delivered: 0,
            receive_address: "73-75 Thủ Khoa Huân, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh 70000, Việt Nam",
            receive_name: "Hoàng",
            receive_phone: "0967123123",
            note: "aaa ",
        }
    ],
    gatheringPackage: [
        {
            id: 0,
            package_id: "VN1235HN",
            send_name: "Dũng",
            send_date: "2023-12-08",
            send_phone: "0912345677",
            send_address: "Tầng 1, Tòa nhà Báo Lao Động, 06 P. Phạm Văn Bạch, Yên Hoà, Cầu Giấy, Hà Nội",
            send_point_id: "0120036",
            receive_name: "Hoàng",
            receive_phone: "09987654321",
            receive_address: "73-75 Thủ Khoa Huân, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh 70000, Việt Nam",
            receive_point_id: "0120040",
            current_from: "gathering",
            from_point_id: "TK0012",
            current_dest: "exchanging",
            dest_point_id: "GD0015",
            status: "received",
            main_cost: 60000,
            other_cost: 10000,
            gtgt_cost: 0,
            other_service_cost: 0,
            total_cost: 77000,
            vat: 10,
            package_type: 1,
            instruction_type: 0,
            weight: 10,
            special_service: '',
            note: 'Hàng dễ vỡ',
            cod: 0,
            receive_other_cost: 0,
            items: [
                {
                    item_name: "Đồng hồ",
                    quantity: 1,
                    value: 100000,
                },
                {
                    item_name: "Điện thoại",
                    quantity: 1,
                    value: 10000000,
                },
            ]
        },
        {
            id: 1,
            package_id: "VN1236HN",
            send_name: "Dũng",
            send_date: "2023-12-07",
            send_phone: "0912345677",
            send_address: "Tầng 1, Tòa nhà Báo Lao Động, 06 P. Phạm Văn Bạch, Yên Hoà, Cầu Giấy, Hà Nội",
            send_point_id: "0120036",
            receive_name: "Hoàng",
            receive_phone: "09987654321",
            receive_address: "73-75 Thủ Khoa Huân, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh 70000, Việt Nam",
            receive_point_id: "0120040",
            current_from: "gathering",
            from_point_id: "TK0012",
            current_dest: "exchanging",
            dest_point_id: "GD0015",
            status: "in-transit",
            main_cost: 80000,
            other_cost: 10000,
            gtgt_cost: 0,
            other_service_cost: 0,
            total_cost: 99000,
            vat: 10,
            package_type: 1,
            instruction_type: null,
            weight: 10,
            special_service: '',
            note: '',
            cod: 0,
            receive_other_cost: 0,
            items: [
            ]
        },
        {
            id: 2,
            package_id: "VN1237HN",
            send_name: "Dũng",
            send_date: "2023-12-10",
            send_phone: "0912345677",
            send_address: "Tầng 1, Tòa nhà Báo Lao Động, 06 P. Phạm Văn Bạch, Yên Hoà, Cầu Giấy, Hà Nội",
            send_point_id: "0120036",
            receive_name: "Hoàng",
            receive_phone: "09987654321",
            receive_address: "73-75 Thủ Khoa Huân, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh 70000, Việt Nam",
            receiving_exchanging_point_id: "0120040",
            current_from: "gathering",
            from_point_id: "TK0012",
            current_dest: "exchanging",
            dest_point_id: "GD0015",
            status: "not-received",
            main_cost: 30000,
            other_cost: 10000,
            gtgt_cost: 0,
            other_service_cost: 0,
            total_cost: 44000,
            vat: 10,
            package_type: 0,
            instruction_type: null,
            weight: 10,
            special_service: '',
            note: '',
            cod: 0,
            receive_other_cost: 0,
            items: [
                {
                    item_name: "Tài liệu",
                    quantity: null,
                    value: 100000,
                },
            ]
        },
    ]
}